### ISSUE TITLE
`-[SKYContainer registerRemoteNotificationDeviceToken:existingDeviceID:completionHandler:]`'s retry makes no differences

### ISSUE THREAD

**Issue by limouren** [SkygearIO/skygear-SDK-iOS#12]
In the SKYContainer's register device method [1], if we try to register an existing device and the server couldn't find the supplied device ID, SKYContainer would re-register the device without supplying the device ID, in an attempt to register a new device.

However, subscription-related operations maintain a default itself, and would supply the device ID if it is not provided in the operation [2]. So SKYContainer's attempt to re-register a new device would fail in vain.

1. https://github.com/SkygearIO/skygear-SDK-iOS/blob/master/Pod/Classes/SKYContainer.m#L509
2. https://github.com/SkygearIO/skygear-SDK-iOS/blob/master/Pod/Classes/Operations/SKYRegisterDeviceOperation.m#L84-L89

**Comment by cheungpat** [comment]
@limouren It is 2016, there is this thing called hyperlink which you can specify text to point to a different hypertext document.

**Comment by limouren** [comment]
@cheungpat，你的資訊真的很有用！

**Comment by cheungpat** [comment]
@limouren https://github.com/SkygearIO/skygear-SDK-iOS/commit/7ffc7c14
