### ISSUE TITLE
Consistent error handling

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/skygear-SDK-iOS#215]
For this issue in iOS, we only need to check if the error handling of current implementation is consistent.

For example, if all the errors are calling the error callback and if all build-in apis and lambda are using error object in error callback.

**Comment by cheungpat** [comment]
Should follow these

https://github.com/search?l=Swift&q=arerror&type=Code
https://deezer.io/whats-right-with-errors-2fe419424f62
https://github.com/apple/swift-evolution/blob/master/proposals/0112-nserror-bridging.md
