### ISSUE TITLE
[SKYDatabase-saveSubscription:completionHandler:] would always fail to save a subscription

### ISSUE THREAD

**Issue by limouren** [SkygearIO/skygear-SDK-iOS#23]
Using the method to save subscription would always lead to the follow error:

```
Error Domain=SKYOperationErrorDomain Code=108 "The server is unable to process the data." UserInfo={SKYErrorName=InvalidArgument, SKYErrorMessage=empty device_id, NSErrorFailingURLKey=http://127.0.0.1:3000/subscription/save, SKYOperationErrorHTTPStatusCodeKey=400, arguments=<CFArray 0x79889ba0 [0x56181f8]>{type = immutable, count = 1, values = (
	0 : <CFString 0x798810f0 [0x56181f8]>{contents = "device_id"}
)}, NSLocalizedDescription=The server is unable to process the data.}
```

skygear-server now requires `subscription:save` to supply `device_id`, but `saveSubscription:completionHandler:` didn't, leading to this error.

**Comment by cheungpat** [comment]
@limouren will you work on this? some information is attached to #26 btw

**Comment by limouren** [comment]
@cheungpat I regard this as an problem on function interface and created PR #24.

If you think it could correctly address #26, merge #24 and we are done.

**Comment by cheungpat** [comment]
@limouren Not sure what “functional interface” means outside the realm of Java.

**Comment by cheungpat** [comment]
The same problem applies to fetch and delete operations, would you be kind enough to fix those too?
