### ISSUE TITLE
Completion handler not called if skygear server died during uploadAsset operation

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/skygear-SDK-iOS#239]
Steps to reproduce:
Kill skygear server during a `uploadAsset` operation

Possible cause:
Early return in `SKYPostAssetOperation.handleRequestCompletionWithData`

**Comment by Steven-Chan** [comment]
@kiootic Please provide some sample code, thanks.

**Comment by kiootic** [comment]
```
            Logger.debug("enter uploadAsset")
            self.container.privateCloudDatabase.uploadAsset(SKYAsset(data: data)) { asset, error in
                Logger.debug("callback uploadAsset")
            }
```
When skygear server is killed during `uploadAsset`, the first log can be seen but second log cannot be seen.

**Comment by Steven-Chan** [comment]
Steps to reproduce in local development setup:
1. Set breakpoint at `SKYDatabase.m` line: 703, i.e. creating `SKYPostAssetOperation`
1. Call skygear database `uploadAsset`, the program should pause at the breakpoint
1. Kill skygear server

`postAssetCompletionBlock` does not get call as expected.
