### ISSUE TITLE
pubsub should have a retry connection options

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-SDK-iOS#27]
Was inspired by this commit: https://github.com/oursky/doorlock/commit/ba23e9958cf0146fd24b6bdf3be6e8b2939d0a54

The developer in the above commit has to explicitly re-subscribe to a channel onConnectionClose()

The SDK maybe should have a default retry value and / or infinity by default?

**Comment by royuen** [comment]
Doc updated in https://github.com/SkygearIO/skygear-doc/pull/305
