### ISSUE TITLE
Crash when use SKYRecordStorage to save a record that contains SKYSequence

### ISSUE THREAD

**Issue by a821246710** [SkygearIO/skygear-SDK-iOS#28]
error message:
```
-[SKYSequence encodeWithCoder:]: unrecognized selector sent to instance 0x7fc9236d42e0
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SKYSequence encodeWithCoder:]: unrecognized selector sent to instance 0x7fc9236d42e0'
```

code:

```swift
let todo = SKYRecord(recordType: "todo")
todo.setObject(title!, forKey: "title")
todo.setObject(SKYSequence(), forKey: "order")
todo.setObject(false, forKey: "done")
            
self.recordStorage.saveRecord(todo)
```

**Comment by cheungpat** [comment]
While `SKYRecordStorage` should not crash saving `SKYSequence`, it probably won’t be sortable, since the value is entirely dependent on server-side state.

**Comment by cheungpat** [comment]
I am not sure why this is happening... can you give me a stack trace or a branch of your code repo so that I can reproduce this? I tried reproducing this but unsuccessful.

**Comment by cheungpat** [comment]
Something like this:

![screen shot 2016-08-23 at 12 42 46 pm](https://cloud.githubusercontent.com/assets/170071/17880573/228600f4-692f-11e6-857f-04b1bc531ecc.png)

see also https://developer.apple.com/library/ios/recipes/xcode_help-breakpoint_navigator/articles/adding_an_exception_breakpoint.html

**Comment by a821246710** [comment]
you may could try this?
https://github.com/a821246710/swift-todo/tree/local-storage
