### ISSUE TITLE
Upgrade to Swift 3

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-SDK-iOS#51]
Tasks:

* Convert Swift example [to use Swift 3 syntax](https://swift.org/migration-guide/)
* Add [nullability annotation](https://developer.apple.com/swift/blog/?id=25) to Objective-C interfaces

**Comment by cheungpat** [comment]
We also need nullability annotation on our Objective-C code, for example, `currentUser` on `SKYContainer` should be `nullable`.

**Comment by chpapa** [comment]
I think this issue is related to the problems on XCode 8 Swift? :)

**Comment by cheungpat** [comment]
Xcode 8 has Swift 3, so this issue is about that, but we don‘t even have very good support for Swift 2, it works, but not very good.

**Comment by chpapa** [comment]
Shall we just shift focus to swift 3? Given Apple probably won't care much
about backward compatibility of swift?

**Comment by cheungpat** [comment]
yea, hence this issue : )

**Comment by chpapa** [comment]
Coooool

**Comment by Steven-Chan** [comment]
follow up issue #120
