### ISSUE TITLE
Container API Key is not attached in `SKYLambdaOperation`

### ISSUE THREAD

**Issue by limouren** [SkygearIO/skygear-SDK-iOS#55]
FYI: https://github.com/SkygearIO/skygear-SDK-iOS/blob/master/Pod/Classes/Operations/SKYLambdaOperation.m#L59

**Comment by limouren** [comment]
As an effect, lambda operation would always fail if user hasn't logged in.

**Comment by cheungpat** [comment]
> As an effect, lambda operation would always fail if user hasn't logged in.

The lambda operation would fail if user hasn’t logged in _and_ if the lambda requires authenticated user.
