### ISSUE TITLE
API/api doc change for register/unregister device

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-SDK-iOS#76]
A developer is confused which API to call for registering/unregistering device:

- `registerRemoteNotificationDeviceToken:completionHandler:`
  - should add a method `registerDeviceWithDeviceToken:completionHandler:` to be consistent with other APIs
  - mention that this method is for registering remote notification (i.e. push notification)
  - mention that app should call `unregisterDeviceCompletionHandler:` to unregister device
- `registerDeviceCompletionHandler:`
  - mention that this method is for registering the device if user denied push notification permission / to register device for pubsub
  - mention that app should call `unregisterDeviceCompletionHandler:` to unregister device
- `unregisterDevice`
  - should be deprecated, call `unregisterDeviceCompletionHandler:` with `nil` parameter
- `unregisterDeviceCompletionHandler:`
  - mention that this method should be called to unregister device

**Comment by b123400** [comment]
Just noticed we already have deregistering device when user logouts, it's strange that we need to call it manually
https://github.com/SkygearIO/skygear-SDK-iOS/blob/ac8532b087a156902e56583aa64a371b02ae2a13/Pod/Classes/SKYContainer.m#L438

**Comment by cheungpat** [comment]
@b123400 Interesting observation. I am going to merge the pull request regardless.
