### ISSUE TITLE
Set mimeType of asset to content-type when fetched from server

### ISSUE THREAD

**Issue by b123400** [SkygearIO/skygear-SDK-iOS#77]
A function implemented in https://github.com/SkygearIO/skygear-server/pull/287

**Comment by rickmak** [comment]
@b123400 I am going to put this to first things since I want to have a minor release on content-type related updates.

**Comment by b123400** [comment]
Are you referring to this issue? https://github.com/SkygearIO/skygear-SDK-iOS/issues/79

**Comment by rickmak** [comment]
So it is duplicated?
