### ISSUE TITLE
Support using NSDictionary as named arguments for callLambda

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-SDK-iOS#89]
As mentioned at SkygearIO/guides#48, Javascript support both array and hashtable for positional / named arguments of Lambda function.

So for consistency, we should support NSDictionary as another callLambda with NSArray.

**Comment by rickmak** [comment]
NSDictionary is supported: http://cocoadocs.org/docsets/SKYKit/0.22.2/Classes/SKYLambdaOperation.html#//api/name/initWithAction:dictionaryArguments:

**Comment by chpapa** [comment]
@rickmak why callLambda doesn't have an nsdictionary version but have to use SKYLambdaOperation?
