### ISSUE TITLE
Add example app in swift

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-SDK-iOS#9]

**Comment by rickmak** [comment]
Let move the current test case sit in `Example` folder to `Tests` folder first. Than add this example in `Example` folder.

**Comment by rickmak** [comment]
Side note: please Keep `pod try SKYKit` working.

**Comment by royuen** [comment]
- [x] Sign up
- [x] Login
- [ ] Query
- [ ] Pubsub
